# diff_drive_controller.yaml
diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.30        # must match hardware (or leave to odom source)
    wheel_radius: 0.05

    # Use commands as wheel angular velocity [rad/s]
    command_interfaces: ["velocity"]
    state_interfaces: ["position", "velocity"]

    # Topic interface
    use_stamped_vel: false
    publish_rate: 50.0

    # Odometry (optional tuning)
    odom_frame_id: odom
    base_frame_id: base_link
    open_loop: false
    pose_covariance_diagonal: [0.001, 0.001, 9999, 9999, 9999, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 9999, 9999, 9999, 0.01]