<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="base_width" value="0.62" />
<xacro:property name="wheel_radius" value="0.17" />
<xacro:property name="wheel_yoff" value="0.13"/>

    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
    
            <!-- Wheel Information -->
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${base_width+(2*wheel_yoff)}</wheel_separation>
            <wheel_diameter>${wheel_radius*2}</wheel_diameter>
    

            <!-- Limits -->
            <max_wheel_torque>200</max_wheel_torque>
            <max_wheel_acceleration>10.0</max_wheel_acceleration>
    

            <!-- Output -->
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
    <!-- <odometry_frame>odom</odometry_frame> -->
    <!-- <robot_base_frame>base_link</robot_base_frame> -->
    
        </plugin>
    </gazebo>

</robot>
