<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<material name="white">
    <color rgba="1 1 1 1"/>
</material>

<material name="orange">
    <color rgba="1 0.3 0.1 1"/>
</material>

<material name="blue">
    <color rgba="0.2 0.2 1 1"/>
</material>

<material name="black">
    <color rgba="0 0 0 1"/>
</material>

<xacro:include filename="inertial_macros.xacro" />

<xacro:property name="base_width" value="0.62" />
<xacro:property name="base_length" value="1.02" />
<xacro:property name="base_height" value="0.51" />
<xacro:property name="wheel_radius" value="0.17" />
<xacro:property name="wheel_width" value="0.1" />
<xacro:property name="wheel_yoff" value="0.13"/>
<xacro:property name="wheel_zoff" value="0.054"/>

<link name="base_link">
</link>



  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

<link name="base_footprint">
</link>
  
  
<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-0.85 0 0"/>
</joint>

<link name="chassis">
    <visual>
        <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
        <material name="white"/>
    </visual>
    
    <collision>
        <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
    </collision>
    
	<xacro:inertial_box mass="0.5" x="${base_length}" y="${base_width}" z="${base_height}">
        <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
	</xacro:inertial_box>
</link>
<gazebo reference="chassis">
    <material>Gazebo/White</material>
</gazebo>

<!-- LEFT WHEEL -->

<joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${base_width/2+wheel_yoff} ${wheel_zoff}" rpy="-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="left_wheel">
    <visual>
        <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <material name="blue"/>
    </visual>
    
    <collision>
        <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
    </collision>
    
    <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>
<gazebo reference="left_wheel">
    <material>Gazebo/Blue</material>
</gazebo>

<!-- RIGHT WHEEL -->

<joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-(base_width/2+wheel_yoff)} ${wheel_zoff}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
</joint>

<link name="right_wheel">
    <visual>
        <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <material name="blue"/>
    </visual>
    
    <collision>
        <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
    </collision>
    
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>
<gazebo reference="right_wheel">
    <material>Gazebo/Blue</material>
</gazebo>

<!-- CASTER WHEEL -->

<joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="0.15 0 ${wheel_zoff}" rpy="0 0 0"/>
</joint>

<link name="caster_wheel">
    <visual>
        <geometry>
            <sphere radius="${wheel_radius}" />
        </geometry>
        <material name="black"/>
    </visual>
    
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}" />
        </geometry>
    </collision>
    
    <xacro:inertial_sphere mass="0.1" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
</link>
<gazebo reference="caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
</gazebo>

</robot>

